services:
  ### MONGO DATABASE
  mongo:
    container_name: mongo
    image: mongo:${MONGO_IMAGE_TAG:-8.0}
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGO_EXTERNAL_PORT:-3300}:27017

volumes:
  mongo_data:
