version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=${PORT}  # uses backend port from .env file
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
