version: "3.8"

##### CONTAINERS #####
services:
  ##### EXPRESS API #####
  backend:
    container_name: backend
    build:
      context: backend
    tty: true
    ports:
      - ${BACKEND_PORT:-3200}:3200
    volumes:
      - ./backend/src:/app/src
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - dbumt

  ##### MONGO DATABASE #####
  mongo:
    container_name: ${MONGO_SERVICE_NAME}
    image: mongo:${MONGO_IMAGE_TAG:-8.0}
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGO_EXTERNAL_PORT:-3300}:27017
    networks:
      - dbumt
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 30s # Perform the health check every 30 seconds.
      timeout: 10s # Consider the health check a failure if it takes more than 10 seconds.
      retries: 5 # Retry the health check up to 5 times before considering the container unhealthy.
      start_period: 10s # How long to wait after the container starts to run the first health check.

  ##### REACT APP #####
  frontend:
    tty: true
    container_name: frontend
    build:
      context: frontend
    ports:
      - ${FRONTEND_PORT:-8080}:80
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - dbumt

##### VOLUMES #####
volumes:
  mongo_data: {}

##### NETWORKS #####
networks:
  dbumt:
    driver: bridge
