name: Frontend React Linting, Formatting, & Build Check

# Restrict GITHUB_TOKEN to read-only access
permissions:
  contents: read # Needed to check out the repository

on:
  pull_request:
    types: [opened, synchronize, ready_for_review] # Triggered by opened or changed pull requests.
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  test-app:
    name: Test Frontend React App
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        # Using v4.0.0 Specifying a specific commit SHA instead of getting the latest version
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2
        with:
          fetch-depth: 0

      # Install dev dependencies
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm i

      # Run linting check with ESLint
      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint

      # Run formatting check with Prettier
      - name: Run Prettier
        working-directory: ./frontend
        run: npm run check

      # Build the frontend APP
      - name: Build Frontend APP
        working-directory: ./frontend
        run: npm run build
