name: Frontend React Linting & Formatting Check

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-lint.yml'
  workflow_dispatch:

jobs:
  lint-api:
    name: Lint Frontend React App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install dev dependencies
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm i --only=dev

      # Run linting check with ESLint
      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint

      # Run formatting check with Prettier
      - name: Run Prettier
        working-directory: ./frontend
        run: npm run check
